env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-mixed-spaces-and-tabs: warn
  no-unused-vars: warn
globals:
  chrome: readonly
  ga: readonly
  angular: readonly
  MediaMetadata: readonly
